pipeline {
    agent any

    stages {
        stage('Build & Tag Docker Image') {
            steps {
                script {
                    withDockerRegistry(credentialsId: 'dockerhub1', toolName: 'docker') {
                        sh "docker build -t rakesh6nm/paymentservice:latest ."
                    }
                }
            }
        }
        
        stage('Push Docker Image') {
            steps {
                script {
                    withDockerRegistry(credentialsId: 'dockerhub1', toolName: 'docker') {
                        sh "docker push rakesh6nm/paymentservice:latest "
                    }
                }
            }
        }
    }
}
